# Generated by Django 4.2.13 on 2026-05-26 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'permissions': [('register_participant', 'Can register participants'), ('change_participant_lab', 'Can change participant lab allocation')]},
        ),
    ]
