# Generated by Django 4.2.13 on 2026-05-26 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registrations', '0002_alter_participant_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'permissions': [('register_participant', 'Can register participants'), ('change_participant_lab', 'Can change participant lab allocation'), ('undo_registration', 'Can undo participant registration')]},
        ),
        migrations.AddField(
            model_name='participant',
            name='regular_sl_number',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('registered', 'Registered'), ('swap', 'Swap'), ('unregistered', 'Unregistered')], default='registered', max_length=20),
        ),
        migrations.CreateModel(
            name='LabCoordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registrations.lab')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
