# Generated by Codex on 2026-05-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0004_session_lab_started_and_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("registered", "Registered"),
                    ("swap", "Swap"),
                    ("unregistered", "Unregistered"),
                    ("rejected", "Rejected"),
                ],
                default="registered",
                max_length=20,
            ),
        ),
    ]
